### PR TITLE
Add second tabpanel

### PR DESCRIPTION
**Pull request by HibaBenAribi**

### CODE REVIEW

**Comment by HibaBenAribi** [comment]
> _ No description provided. _

image

**Comment by msarrias** [comment]
Hi @HibaBenAribi,

good job! Some comments:

- As you can see in the pic the table and histogram overlap, what could it be? 

image

**Comment by msarrias** [comment]
@HibaBenAribi 
I think we should not ask for a dir, the directories should be handled by the package, I'm sure there's a way to do that, anyway,

If I run:

`VariantSurvival("~/Desktop/VariantSurvival/VariantSurvival_package/R", demo=TRUE)`


It looks like this:

image

image

**Comment by msarrias** [comment]
@HibaBenAribi some more comments:
- In the first tab, can you move the table below the plot? Remember that the user should be able to add more columns, so that will require a bit more of space.
- Can you take away the dir param in the VariantSurvival function.
I think we can merge after that.

**Comment by HibaBenAribi** [comment]
> @HibaBenAribi some more comments:
> 
> * In the first tab, can you move the table below/above (whichever you prefer) the plot? Remember that the user should be able to add more columns, so that will require a bit more of space.
> * Can you take away the dir param in the VariantSurvival function.
>   I think we can merge after that.

Done

**Comment by Krannich479** [comment]
I'll look into the new interface asap

**Comment by Krannich479** [comment]
I installed `devtools::install_github("collaborativebioinformatics/VariantSurvival/VariantSurvival_package@Hiba-patch-1")` and for me the tabs are still one under another and not actual tabs. Is this only on my side? 

Another general question: what is an _identifier factor_? Does this mean patient ID?

**Comment by msarrias** [comment]
@Krannich479 yes, the identifier factor refers to the patient ID! would you suggest changing it to something different?

**Review by msarrias — APPROVED** [review]

**Pull request merged**
