### PR TITLE
[Error] error in ensembleTogenes.csv

### PR DESCRIPTION
**Pull request by Krannich479**
- ENSG00000120948 maps to two distinct gene: TARDBP, TDP43
- all other duplicates have been deleted

-----------------------------
PLEASE DON'T MERGE YET!

### CODE REVIEW

**Comment by Krannich479** [comment]
@HibaBenAribi the Ensemble ID "ENSG00000120948" in that file maps to two distinct genes. Please resolve this before we can merge this to the code base.

**Comment by HibaBenAribi** [comment]
> @HibaBenAribi the Ensemble ID "ENSG00000120948" in that file maps to two distinct genes. Please resolve this before we can merge this to the code base.

Corrected

**Comment by msarrias** [comment]
According to [Ensembl](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000120948;r=1:11012344-11030528) TDP-43 and TARDBP are synonymous genes. Are these two referring to the same gene?

**Comment by HibaBenAribi** [comment]
> According to [Ensembl](https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000120948;r=1:11012344-11030528) TDP-43 and TARDBP are synonymous genes. Are these two referring to the same gene?

 it was a mistake , the right gene is TARDBP

**Comment by Krannich479** [comment]
commit 57abbda3dccbadffc067f693bfbea628f90bfc13 solved this

**Pull request closed without merging**
