### PR TITLE
Add new diseases +Update first tab

### PR DESCRIPTION
**Pull request by HibaBenAribi**
1. first tab include disease-gene association info 
image

2. + select gene
image

3. the second and third tabs are the same

4. I deleted the old diseases gene since we do not have a confirmed association yet. We can add them later if Ahmad provide the source.

Note : try the demo with the gene DAO
Note : the modifications in Marina's PR are included

### CODE REVIEW

**Comment by Krannich479** [comment]
Hi Hiba, 
I looked into your PR this morning and unfortunately I cannot reproduce the functionality of your branch yet.
Once I choose the "disease of interest" I can see your new layout (Screenshot 1) but once I make a selection for the time factor and unit the dashboard breaks. Tested on MacOS with R 4.0.5, same behavior with both RStudio as well as from within browser.

**Comment by Krannich479** [comment]
"""
Warning: Error in : The `.data` argument of `add_column()` must have unique names as of tibble
3.0.0.
"""
Is an error message I get in the background once things break.

**Comment by Krannich479** [comment]
Also " Note : the modifications in Marina's PR are included". Do you refer to PR #21 ?

**Comment by HibaBenAribi** [comment]
> Hi Hiba, I looked into your PR this morning and unfortunately I cannot reproduce the functionality of your branch yet. Once I choose the "disease of interest" I can see your new layout (Screenshot 1) but once I make a selection for the time factor and unit the dashboard breaks. Tested on MacOS with R 4.0.5, same behavior with both RStudio as well as from within browser.

Hi Thomas, Please consider updating all the files, because it works for me. 
This PR is to suggest the first tab layout . the second and third tab code is similar to Marina's PR #21

**Comment by msarrias** [comment]
Can't run this version of the code. 

Apparently the " ‘disease_gene.xlsx’" is used somewhere but the file was removed.

**Comment by HibaBenAribi** [comment]
> the file is restored

 I can't find a way to define a fixed size of the figures because it depends on the pc monitor size, but it changes if you zoom out

**Comment by msarrias** [comment]
@HibaBenAribi I don't have the same disease name as the one shown in this figure:

>    image
When I run your code the biomarkers table does not populate.

**Pull request closed without merging**
